### ISSUE TITLE
Get my-courses suggestions??

### ISSUE THREAD

**Issue by ngankhanh98** [ngankhanh98/coursebox-angular#3]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request
* [x] question about the decisions made in the repository

### Issue description

**Current situation:**
Currently, we have 2 big modules: `pages` and `auth`, each has their own Akita's state: 
```ts
// auth.ts (state for AuthModule)
export interface Auth {
  username: string;
  fullname: string;
  userId: string;

  token: string;
}

// course.ts (state for PagesModule)
import { Auth } from 'app/auth/state/auth';

export interface Course {
  courseId: string;
  title: string;
  teacher: Auth;
}
```

**Expected behavior:**
In route: `/attend/my-courses`, I expect to see courses created by me. To doing so, `auth.userId` or `auth.username` should be retrieve; and `course` should returns to all course, then querying them both

**Solution suggests:**
1. Rewrite an api (GET - /course/{userId}), and maybe install another store state
2. Find the way to query the expected result from 2 store state using Akita query. In doing this, I found myself being confused about: where to install code properly, in **my-courses.component.ts** or in **state/course.service.ts**
 2.1. And do I have the kind of query allowing to use filter based on 2 Observerable (one with auth state, and the other with course state)?

__
Currently, I'm doging my 2nd approach. The above drawbacks are what I faced or am facing with. Besides, I would like to know if these 2 solutions are anti-pattern (because I have no idea).
@dohoangdinhtien

**Comment by dohoangdinhtien** [comment]
Hi Khánh,

1. Nestjs side, you need to make new API to get my course (based on JWT token, we can get userId. Then we will make filter the course with it).
2. Angular side, add new myCourse interface extend from Course interface.

**Comment by ngankhanh98** [comment]
Yes, and with the first solution, I believe I need to install a new state or else,  modify `course state` to store `my-course` from called API. Then, when I create my course, 2 sources of state need to be updated: all-course and my-course. Part of me thinks this way is antithesis to Single source of truth priciple.

I think I will follow your 2nd direction, to efficiently use the power of Akita query. Thank you sir!!!
